### ISSUE TITLE
[AirDeviceId] Error - Extension Context is null.

### ISSUE THREAD

**Issue by wyseburn** [freshplanet/ANE-DeviceId#22]
I try "rebuilt bin with air 17 release" version.

I test by airsdk17, airsdk15, airsdk3.9 

17, 15 error "[AirDeviceId] Error - Extension Context is null."

3.9 error "Invalid namespace  http://ns.adobe.com/air/extension/15.0"

plz

**Comment by jauboux** [comment]
I get the same error on android devices, meaning the ane is completely useless on this platform. Did you manage to make it work without debugging the java source ? Otherwise I'm considering using the mac address
Thanks

**Comment by wyseburn** [comment]
Sorry. I don't speek english.. :(
I use previous version. It's Ok

https://github.com/freshplanet/ANE-DeviceId/blob/f780c8a94f3abe958ebc003b6ac47497a9b27f79/bin/AirDeviceId.ane
